-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AgenciaVeiculosBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AgenciaVeiculosBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgenciaVeiculosBD` DEFAULT CHARACTER SET utf8 ;
USE `AgenciaVeiculosBD` ;

-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`RETIRADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`RETIRADA` (
  `idRETIRADA` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`idRETIRADA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`DEVOLUCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`DEVOLUCAO` (
  `idDEVOLUCAO` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`idDEVOLUCAO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`ALUGUEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`ALUGUEL` (
  `idALUGAR` INT NOT NULL,
  `RETIRADA_idRETIRADA1` INT NOT NULL,
  `DEVOLUCAO_idDEVOLUCAO1` INT NOT NULL,
  PRIMARY KEY (`idALUGAR`, `RETIRADA_idRETIRADA1`, `DEVOLUCAO_idDEVOLUCAO1`),
  INDEX `fk_ALUGUEL_RETIRADA1_idx` (`RETIRADA_idRETIRADA1` ASC) VISIBLE,
  INDEX `fk_ALUGUEL_DEVOLUCAO1_idx` (`DEVOLUCAO_idDEVOLUCAO1` ASC) VISIBLE,
  CONSTRAINT `fk_ALUGUEL_RETIRADA1`
    FOREIGN KEY (`RETIRADA_idRETIRADA1`)
    REFERENCES `AgenciaVeiculosBD`.`RETIRADA` (`idRETIRADA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUGUEL_DEVOLUCAO1`
    FOREIGN KEY (`DEVOLUCAO_idDEVOLUCAO1`)
    REFERENCES `AgenciaVeiculosBD`.`DEVOLUCAO` (`idDEVOLUCAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`MOVIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`MOVIMENTO` (
  `idMOVIMENTO` INT GENERATED ALWAYS AS (Contrato),
  `valor` DECIMAL UNSIGNED NULL,
  `dataContrato` DATE NULL,
  `ALUGUEL_idALUGAR` INT NOT NULL,
  `ALUGUEL_RETIRADA_idRETIRADA1` INT NOT NULL,
  `ALUGUEL_DEVOLUCAO_idDEVOLUCAO1` INT NOT NULL,
  `seguro` DECIMAL NULL,
  PRIMARY KEY (`idMOVIMENTO`, `ALUGUEL_idALUGAR`, `ALUGUEL_RETIRADA_idRETIRADA1`, `ALUGUEL_DEVOLUCAO_idDEVOLUCAO1`),
  INDEX `fk_MOVIMENTO_ALUGUEL1_idx` (`ALUGUEL_idALUGAR` ASC, `ALUGUEL_RETIRADA_idRETIRADA1` ASC, `ALUGUEL_DEVOLUCAO_idDEVOLUCAO1` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIMENTO_ALUGUEL1`
    FOREIGN KEY (`ALUGUEL_idALUGAR` , `ALUGUEL_RETIRADA_idRETIRADA1` , `ALUGUEL_DEVOLUCAO_idDEVOLUCAO1`)
    REFERENCES `AgenciaVeiculosBD`.`ALUGUEL` (`idALUGAR` , `RETIRADA_idRETIRADA1` , `DEVOLUCAO_idDEVOLUCAO1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`CLIENTES` (
  `idCPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NOT NULL,
  `MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idCPF`, `MOVIMENTO_idMOVIMENTO`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_CLIENTE_MOVIMENTO1_idx` (`MOVIMENTO_idMOVIMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_MOVIMENTO1`
    FOREIGN KEY (`MOVIMENTO_idMOVIMENTO`)
    REFERENCES `AgenciaVeiculosBD`.`MOVIMENTO` (`idMOVIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`FUNCIONARIO` (
  `idMatricula` INT GENERATED ALWAYS AS (ID),
  `Cargo` VARCHAR(45) NOT NULL,
  `MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idMatricula`, `MOVIMENTO_idMOVIMENTO`),
  INDEX `fk_FUNCIONARIO_MOVIMENTO1_idx` (`MOVIMENTO_idMOVIMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIO_MOVIMENTO1`
    FOREIGN KEY (`MOVIMENTO_idMOVIMENTO`)
    REFERENCES `AgenciaVeiculosBD`.`MOVIMENTO` (`idMOVIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`CORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`CORES` (
  `idcor` INT GENERATED ALWAYS AS (COR) VIRTUAL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`MARCAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`MARCAS` (
  `idmarca` INT GENERATED ALWAYS AS (MARCA) VIRTUAL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`MODELOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`MODELOS` (
  `idMODELOS` INT GENERATED ALWAYS AS (MODELO),
  `nome` VARCHAR(45) NULL,
  `MARCAS_idmarca` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMODELOS`, `MARCAS_idmarca`),
  INDEX `fk_MODELOS_MARCAS1_idx` (`MARCAS_idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_MODELOS_MARCAS1`
    FOREIGN KEY (`MARCAS_idmarca`)
    REFERENCES `AgenciaVeiculosBD`.`MARCAS` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`VEICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`VEICULOS` (
  `idPlaca` VARCHAR(8) NOT NULL,
  `ano` INT NULL,
  `kmrodados` INT NOT NULL,
  `CORES_idcor` INT UNSIGNED NOT NULL,
  `MODELOS_idMODELOS` INT NOT NULL,
  `MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idPlaca`, `CORES_idcor`, `MODELOS_idMODELOS`, `MOVIMENTO_idMOVIMENTO`),
  INDEX `fk_VEICULOS_CORES_idx` (`CORES_idcor` ASC) VISIBLE,
  INDEX `fk_VEICULOS_MODELOS1_idx` (`MODELOS_idMODELOS` ASC) VISIBLE,
  INDEX `fk_VEICULOS_MOVIMENTO1_idx` (`MOVIMENTO_idMOVIMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULOS_CORES`
    FOREIGN KEY (`CORES_idcor`)
    REFERENCES `AgenciaVeiculosBD`.`CORES` (`idcor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULOS_MODELOS1`
    FOREIGN KEY (`MODELOS_idMODELOS`)
    REFERENCES `AgenciaVeiculosBD`.`MODELOS` (`idMODELOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULOS_MOVIMENTO1`
    FOREIGN KEY (`MOVIMENTO_idMOVIMENTO`)
    REFERENCES `AgenciaVeiculosBD`.`MOVIMENTO` (`idMOVIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`OFICINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`OFICINA` (
  `idOFICINA` INT GENERATED ALWAYS AS (OFICINA) VIRTUAL,
  `nome` VARCHAR(25) NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `VEICULOS_idPlaca` VARCHAR(8) NOT NULL,
  `VEICULOS_CORES_idcor` INT UNSIGNED NOT NULL,
  `VEICULOS_MODELOS_idMODELOS` INT NOT NULL,
  `VEICULOS_MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idOFICINA`, `VEICULOS_idPlaca`, `VEICULOS_CORES_idcor`, `VEICULOS_MODELOS_idMODELOS`, `VEICULOS_MOVIMENTO_idMOVIMENTO`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE,
  INDEX `fk_OFICINA_VEICULOS1_idx` (`VEICULOS_idPlaca` ASC, `VEICULOS_CORES_idcor` ASC, `VEICULOS_MODELOS_idMODELOS` ASC, `VEICULOS_MOVIMENTO_idMOVIMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_OFICINA_VEICULOS1`
    FOREIGN KEY (`VEICULOS_idPlaca` , `VEICULOS_CORES_idcor` , `VEICULOS_MODELOS_idMODELOS` , `VEICULOS_MOVIMENTO_idMOVIMENTO`)
    REFERENCES `AgenciaVeiculosBD`.`VEICULOS` (`idPlaca` , `CORES_idcor` , `MODELOS_idMODELOS` , `MOVIMENTO_idMOVIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`LAVAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`LAVAGEM` (
  `idLAVAGEM` INT GENERATED ALWAYS AS (LAVAGEM) VIRTUAL,
  `data` DATE NOT NULL,
  `vlrLavagem` DECIMAL UNSIGNED NOT NULL,
  `OFICINA_idOFICINA` INT UNSIGNED NOT NULL,
  `OFICINA_VEICULOS_idPlaca` VARCHAR(8) NOT NULL,
  `OFICINA_VEICULOS_CORES_idcor` INT UNSIGNED NOT NULL,
  `OFICINA_VEICULOS_MODELOS_idMODELOS` INT NOT NULL,
  `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idLAVAGEM`, `OFICINA_idOFICINA`, `OFICINA_VEICULOS_idPlaca`, `OFICINA_VEICULOS_CORES_idcor`, `OFICINA_VEICULOS_MODELOS_idMODELOS`, `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO`),
  INDEX `fk_LAVAR_OFICINA1_idx` (`OFICINA_idOFICINA` ASC, `OFICINA_VEICULOS_idPlaca` ASC, `OFICINA_VEICULOS_CORES_idcor` ASC, `OFICINA_VEICULOS_MODELOS_idMODELOS` ASC, `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_LAVAR_OFICINA1`
    FOREIGN KEY (`OFICINA_idOFICINA` , `OFICINA_VEICULOS_idPlaca` , `OFICINA_VEICULOS_CORES_idcor` , `OFICINA_VEICULOS_MODELOS_idMODELOS` , `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO`)
    REFERENCES `AgenciaVeiculosBD`.`OFICINA` (`idOFICINA` , `VEICULOS_idPlaca` , `VEICULOS_CORES_idcor` , `VEICULOS_MODELOS_idMODELOS` , `VEICULOS_MOVIMENTO_idMOVIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


-- -----------------------------------------------------
-- Table `AgenciaVeiculosBD`.`MANUTENCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgenciaVeiculosBD`.`MANUTENCAO` (
  `idMANUTENCAO` INT GENERATED ALWAYS AS (MANUTENCAO) VIRTUAL,
  `data` DATE NOT NULL,
  `vlrManutencao` DECIMAL UNSIGNED NOT NULL,
  `OFICINA_idOFICINA` INT UNSIGNED NOT NULL,
  `OFICINA_VEICULOS_idPlaca` VARCHAR(8) NOT NULL,
  `OFICINA_VEICULOS_CORES_idcor` INT UNSIGNED NOT NULL,
  `OFICINA_VEICULOS_MODELOS_idMODELOS` INT NOT NULL,
  `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idMANUTENCAO`, `OFICINA_idOFICINA`, `OFICINA_VEICULOS_idPlaca`, `OFICINA_VEICULOS_CORES_idcor`, `OFICINA_VEICULOS_MODELOS_idMODELOS`, `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO`),
  INDEX `fk_MANUTENCAO_OFICINA1_idx` (`OFICINA_idOFICINA` ASC, `OFICINA_VEICULOS_idPlaca` ASC, `OFICINA_VEICULOS_CORES_idcor` ASC, `OFICINA_VEICULOS_MODELOS_idMODELOS` ASC, `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_MANUTENCAO_OFICINA1`
    FOREIGN KEY (`OFICINA_idOFICINA` , `OFICINA_VEICULOS_idPlaca` , `OFICINA_VEICULOS_CORES_idcor` , `OFICINA_VEICULOS_MODELOS_idMODELOS` , `OFICINA_VEICULOS_MOVIMENTO_idMOVIMENTO`)
    REFERENCES `AgenciaVeiculosBD`.`OFICINA` (`idOFICINA` , `VEICULOS_idPlaca` , `VEICULOS_CORES_idcor` , `VEICULOS_MODELOS_idMODELOS` , `VEICULOS_MOVIMENTO_idMOVIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_icelandic_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
